# Assignment 9

In [1]:
# Numpy:

# Create a NumPy array and perform various operations like addition, subtraction, multiplication, and division.
# Explore indexing and slicing to access specific elements or subsets of the array.
# Practice reshaping arrays and transposing matrices.
# Use NumPy functions to calculate statistics like mean, median, standard deviation, and variance.
# Create arrays with different data types (e.g., int, float, bool, str).
# Concatenate arrays.
# Sort arrays in ascending or descending order.

# Pandas:

# Load data from various sources (e.g., CSV, Excel, JSON).
# Explore the structure of a DataFrame, including its shape, data types, and missing values.
# Summarize the data using descriptive statistics.
# Filter and select specific columns or rows.

In [2]:
import numpy as np

In [3]:
numpy_list = np.array([1,2,3,4,5])

In [6]:
# Addition
addition_list = numpy_list + 2
print(addition_list)

# Subtraction
subtraction_list = numpy_list - 2
print(subtraction_list)

# Multiplication
multiplication_list = numpy_list * 2
print(multiplication_list)

# Division
division_list = numpy_list / 2
print(division_list)

# Indexing
print(numpy_list[1])

# Slicing
print(numpy_list[1:4])

# Shape
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr_shape = np_array.shape
print(arr_shape)

# Reshape
arr_to_reshape = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
reshaped_arr = arr_to_reshape.reshape(3,4)
print(reshaped_arr)

# Transposing
transposed_arr = reshaped_arr.T
print(transposed_arr)

numpy_list = np.array([1,2,3,4,5])

# Mean
numpy_list_mean = np.mean(numpy_list)
print(numpy_list_mean)

# Median
numpy_list_median = np.median(numpy_list)
print(numpy_list_median)

# Standard Deviation
numpy_list_std = np.std(numpy_list)
print(numpy_list_std)

# Arrays with different data types
np_int_array = np.array([1,2,3,4,5])
np_float_array = np.array([1.9,2.6,3.1,4.3,5.4])
np_bool_array = np.array([True,False,True,False,True])
np_str_array = np.array(['string 1','string 2','string 3','string 4','string 5',])
np_mix_array = np.array([1, 2.2, True, "string"])

# Concatenate array
concatenated_array = np.concatenate((np_int_array, np_float_array,np_bool_array,np_str_array,np_mix_array))
print(concatenated_array)

# Sort arrays in ascending or descending order.
numpy_list = np.array([5,3,2,4,1])

asc_arr = np.sort(numpy_list)
dsc_arr = asc_arr[::-1]
print(asc_arr)
print(dsc_arr)

[3 4 5 6 7]
[-1  0  1  2  3]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]
2
[2 3 4]
(12,)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
3.0
3.0
1.4142135623730951
['1' '2' '3' '4' '5' '1.9' '2.6' '3.1' '4.3' '5.4' 'True' 'False' 'True'
 'False' 'True' 'string 1' 'string 2' 'string 3' 'string 4' 'string 5' '1'
 '2.2' 'True' 'string']
[1 2 3 4 5]
[5 4 3 2 1]


In [ ]:
import pandas as pd

In [ ]:
df_csv = pd.read_csv('student_data.csv')
print(df_csv)

In [ ]:
df_excel = pd.read_excel('student_data.xlsx')
print(df_excel)

In [ ]:
df_json = pd.read_json('student_data.json')
print(df_json)

In [ ]:
# Shape
shape = df_csv.shape
print("Shape of the DataFrame:", shape)

# Type
data_types = df_csv.dtypes
print("Data Types of the DataFrame:\n", data_types)

# Missing values
missing_values = df_csv.isnull().sum()
print("Missing Values in the DataFrame:\n", missing_values)

# Data Summary
data_summary = df_csv.describe()
print("Descriptive Statistics for All Columns:\n", data_summary)

# Filter & Select
first_col = df_csv['roll no']
print(first_col)

words_starts_with_a = df_csv[df_csv['Name'].str.startswith('A')]
print(words_starts_with_a)

In [8]:
import sys

num = 42
print("Size of num:", sys.getsizeof(num))

Size of num: 28
