# Assignment 9

In [ ]:
# Numpy:

# Create a NumPy array and perform various operations like addition, subtraction, multiplication, and division.
# Explore indexing and slicing to access specific elements or subsets of the array.
# Practice reshaping arrays and transposing matrices.
# Use NumPy functions to calculate statistics like mean, median, standard deviation, and variance.
# Create arrays with different data types (e.g., int, float, bool, str).
# Concatenate arrays.
# Sort arrays in ascending or descending order.

# Pandas:

# Load data from various sources (e.g., CSV, Excel, JSON).
# Explore the structure of a DataFrame, including its shape, data types, and missing values.
# Summarize the data using descriptive statistics.
# Filter and select specific columns or rows.

In [3]:
import numpy as np

In [4]:
numpy_list = np.array([1,2,3,4,5])

In [27]:
# Addition
addition_list = numpy_list + 2
print(addition_list)

# Subtraction
subtraction_list = numpy_list - 2
print(subtraction_list)

# Multiplication
multiplication_list = numpy_list * 2
print(multiplication_list)

# Division
division_list = numpy_list / 2
print(division_list)

# Indexing
print(numpy_list[1])

# Slicing
print(numpy_list[1:4])

# Reshape
arr_to_reshape = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
reshaped_arr = arr_to_reshape.reshape(3,4)
print(reshaped_arr)

# Transposing
transposed_arr = reshaped_arr.T
print(transposed_arr)

numpy_list = np.array([1,2,3,4,5])

# Mean
numpy_list_mean = np.mean(numpy_list)
print(numpy_list_mean)

# Median
numpy_list_median = np.median(numpy_list)
print(numpy_list_median)

# Standard Deviation
numpy_list_std = np.std(numpy_list)
print(numpy_list_std)

# Arrays with different data types
np_int_array = np.array([1,2,3,4,5])
np_float_array = np.array([1.9,2.6,3.1,4.3,5.4])
np_bool_array = np.array([True,False,True,False,True])
np_str_array = np.array(['string 1','string 2','string 3','string 4','string 5',])
np_mix_array = np.array([1, 2.2, True, "string"])

# Concatenate array
concatenated_array = np.concatenate((np_int_array, np_float_array,np_bool_array,np_str_array,np_mix_array))
print(concatenated_array)

# Sort arrays in ascending or descending order.
numpy_list = np.array([5,3,2,4,1])

asc_arr = np.sort(numpy_list)
dsc_arr = asc_arr[::-1]
print(asc_arr)
print(dsc_arr)

[7 5 4 6 3]
[ 3  1  0  2 -1]
[10  6  4  8  2]
[2.5 1.5 1.  2.  0.5]
3
[3 2 4]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
3.0
3.0
1.4142135623730951
['1' '2' '3' '4' '5' '1.9' '2.6' '3.1' '4.3' '5.4' 'True' 'False' 'True'
 'False' 'True' 'string 1' 'string 2' 'string 3' 'string 4' 'string 5' '1'
 '2.2' 'True' 'string']
[1 2 3 4 5]
[5 4 3 2 1]


In [2]:
import pandas as pd

In [31]:
df_csv = pd.read_csv('student_data.csv')
print(df_csv)

    roll no       Name  Chemistry  Physics  Math
0       101      Aliza         50       23    87
1       102     Fareed         45       24    88
2       103      Basit         46       25    89
3       104   Abdullah         47       26    90
4       105        Ali         48       27    67
5       106   Mubashir         49       28    68
6       107     Waleed         50       29    69
7       108    Mansoor         51       30    70
8       109       Zain         52       31    71
9       110     Mohsin         53       67    72
10      111   Shahmeer         54       68    73
11      112        Rao         55       69    74
12      113  Aurangzeb         56       70    75
13      114    Zeeshan         57       71    76
14      115      Hamna         58       72    77
15      116      Hamza         59       73    78
16      117     Khalid         60       74    79
17      118     Behroz         61       75    80
18      119     Justin         62       76    81
19      120     Dani

In [9]:
df_excel = pd.read_excel('student_data.xlsx')
print(df_excel)

    roll no       Name  Chemistry  Physics  Math
0       101      Aliza         50       23    87
1       102     Fareed         45       24    88
2       103      Basit         46       25    89
3       104   Abdullah         47       26    90
4       105        Ali         48       27    67
5       106   Mubashir         49       28    68
6       107     Waleed         50       29    69
7       108    Mansoor         51       30    70
8       109       Zain         52       31    71
9       110     Mohsin         53       67    72
10      111   Shahmeer         54       68    73
11      112        Rao         55       69    74
12      113  Aurangzeb         56       70    75
13      114    Zeeshan         57       71    76
14      115      Hamna         58       72    77
15      116      Hamza         59       73    78
16      117     Khalid         60       74    79
17      118     Behroz         61       75    80
18      119     Justin         62       76    81
19      120     Dani

In [10]:
df_json = pd.read_json('student_data.json')
print(df_json)

    roll_no       Name  Chemistry  Physics  Math
0       101      Aliza         50       23    87
1       102     Fareed         45       24    88
2       103      Basit         46       25    89
3       104   Abdullah         47       26    90
4       105        Ali         48       27    67
5       106   Mubashir         49       28    68
6       107     Waleed         50       29    69
7       108    Mansoor         51       30    70
8       109       Zain         52       31    71
9       110     Mohsin         53       67    72
10      111   Shahmeer         54       68    73
11      112        Rao         55       69    74
12      113  Aurangzeb         56       70    75
13      114    Zeeshan         57       71    76
14      115      Hamna         58       72    77
15      116      Hamza         59       73    78
16      117     Khalid         60       74    79
17      118     Behroz         61       75    80
18      119     Justin         62       76    81
19      120     Dani

In [46]:
# Shape
shape = df_csv.shape
print("Shape of the DataFrame:", shape)

# Type
data_types = df_csv.dtypes
print("Data Types of the DataFrame:\n", data_types)

# Missing values
missing_values = df_csv.isnull().sum()
print("Missing Values in the DataFrame:\n", missing_values)

# Data Summary
data_summary = df_csv.describe()
print("Descriptive Statistics for All Columns:\n", data_summary)

# Filter & Select
first_col = df_csv['roll no']
print(first_col)

words_starts_with_a = df_csv[df_csv['Name'].str.startswith('A')]
print(words_starts_with_a)

Shape of the DataFrame: (50, 5)
Data Types of the DataFrame:
 roll no       int64
Name         object
Chemistry     int64
Physics       int64
Math          int64
dtype: object
Missing Values in the DataFrame:
 roll no      0
Name         0
Chemistry    0
Physics      0
Math         0
dtype: int64
Descriptive Statistics for All Columns:
          roll no  Chemistry    Physics       Math
count   50.00000  50.000000  50.000000  50.000000
mean   125.50000  68.420000  65.060000  77.360000
std     14.57738  14.116266  22.676437  14.789351
min    101.00000  45.000000  23.000000  45.000000
25%    113.25000  56.250000  47.500000  71.250000
50%    125.50000  68.500000  73.500000  79.000000
75%    137.75000  80.750000  82.750000  88.750000
max    150.00000  92.000000  92.000000  98.000000
0     101
1     102
2     103
3     104
4     105
5     106
6     107
7     108
8     109
9     110
10    111
11    112
12    113
13    114
14    115
15    116
16    117
17    118
18    119
19    120
20    121
2